# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/haas/Documents/Masters/CompPhys2/neural_quantum_state

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/haas/Documents/Masters/CompPhys2/neural_quantum_state

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/lib/python3.10/site-packages/cmake/data/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haas/Documents/Masters/CompPhys2/neural_quantum_state/CMakeFiles /Users/haas/Documents/Masters/CompPhys2/neural_quantum_state//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haas/Documents/Masters/CompPhys2/neural_quantum_state/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Vmclib

# Build rule for target.
Vmclib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vmclib
.PHONY : Vmclib

# fast build rule for target.
Vmclib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/build
.PHONY : Vmclib/fast

#=============================================================================
# Target rules for targets named vmc

# Build rule for target.
vmc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vmc
.PHONY : vmc

# fast build rule for target.
vmc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vmc.dir/build.make CMakeFiles/vmc.dir/build
.PHONY : vmc/fast

#=============================================================================
# Target rules for targets named timing

# Build rule for target.
timing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timing
.PHONY : timing

# fast build rule for target.
timing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timing.dir/build.make CMakeFiles/timing.dir/build
.PHONY : timing/fast

Hamiltonians/anharmonicoscillator.o: Hamiltonians/anharmonicoscillator.cpp.o
.PHONY : Hamiltonians/anharmonicoscillator.o

# target to build an object file
Hamiltonians/anharmonicoscillator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/anharmonicoscillator.cpp.o
.PHONY : Hamiltonians/anharmonicoscillator.cpp.o

Hamiltonians/anharmonicoscillator.i: Hamiltonians/anharmonicoscillator.cpp.i
.PHONY : Hamiltonians/anharmonicoscillator.i

# target to preprocess a source file
Hamiltonians/anharmonicoscillator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/anharmonicoscillator.cpp.i
.PHONY : Hamiltonians/anharmonicoscillator.cpp.i

Hamiltonians/anharmonicoscillator.s: Hamiltonians/anharmonicoscillator.cpp.s
.PHONY : Hamiltonians/anharmonicoscillator.s

# target to generate assembly for a file
Hamiltonians/anharmonicoscillator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/anharmonicoscillator.cpp.s
.PHONY : Hamiltonians/anharmonicoscillator.cpp.s

Hamiltonians/harmonicoscillator.o: Hamiltonians/harmonicoscillator.cpp.o
.PHONY : Hamiltonians/harmonicoscillator.o

# target to build an object file
Hamiltonians/harmonicoscillator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/harmonicoscillator.cpp.o
.PHONY : Hamiltonians/harmonicoscillator.cpp.o

Hamiltonians/harmonicoscillator.i: Hamiltonians/harmonicoscillator.cpp.i
.PHONY : Hamiltonians/harmonicoscillator.i

# target to preprocess a source file
Hamiltonians/harmonicoscillator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/harmonicoscillator.cpp.i
.PHONY : Hamiltonians/harmonicoscillator.cpp.i

Hamiltonians/harmonicoscillator.s: Hamiltonians/harmonicoscillator.cpp.s
.PHONY : Hamiltonians/harmonicoscillator.s

# target to generate assembly for a file
Hamiltonians/harmonicoscillator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Hamiltonians/harmonicoscillator.cpp.s
.PHONY : Hamiltonians/harmonicoscillator.cpp.s

InitialStates/initialstate.o: InitialStates/initialstate.cpp.o
.PHONY : InitialStates/initialstate.o

# target to build an object file
InitialStates/initialstate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/InitialStates/initialstate.cpp.o
.PHONY : InitialStates/initialstate.cpp.o

InitialStates/initialstate.i: InitialStates/initialstate.cpp.i
.PHONY : InitialStates/initialstate.i

# target to preprocess a source file
InitialStates/initialstate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/InitialStates/initialstate.cpp.i
.PHONY : InitialStates/initialstate.cpp.i

InitialStates/initialstate.s: InitialStates/initialstate.cpp.s
.PHONY : InitialStates/initialstate.s

# target to generate assembly for a file
InitialStates/initialstate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/InitialStates/initialstate.cpp.s
.PHONY : InitialStates/initialstate.cpp.s

Solvers/metropolis.o: Solvers/metropolis.cpp.o
.PHONY : Solvers/metropolis.o

# target to build an object file
Solvers/metropolis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolis.cpp.o
.PHONY : Solvers/metropolis.cpp.o

Solvers/metropolis.i: Solvers/metropolis.cpp.i
.PHONY : Solvers/metropolis.i

# target to preprocess a source file
Solvers/metropolis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolis.cpp.i
.PHONY : Solvers/metropolis.cpp.i

Solvers/metropolis.s: Solvers/metropolis.cpp.s
.PHONY : Solvers/metropolis.s

# target to generate assembly for a file
Solvers/metropolis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolis.cpp.s
.PHONY : Solvers/metropolis.cpp.s

Solvers/metropolishastings.o: Solvers/metropolishastings.cpp.o
.PHONY : Solvers/metropolishastings.o

# target to build an object file
Solvers/metropolishastings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolishastings.cpp.o
.PHONY : Solvers/metropolishastings.cpp.o

Solvers/metropolishastings.i: Solvers/metropolishastings.cpp.i
.PHONY : Solvers/metropolishastings.i

# target to preprocess a source file
Solvers/metropolishastings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolishastings.cpp.i
.PHONY : Solvers/metropolishastings.cpp.i

Solvers/metropolishastings.s: Solvers/metropolishastings.cpp.s
.PHONY : Solvers/metropolishastings.s

# target to generate assembly for a file
Solvers/metropolishastings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/metropolishastings.cpp.s
.PHONY : Solvers/metropolishastings.cpp.s

Solvers/montecarlo.o: Solvers/montecarlo.cpp.o
.PHONY : Solvers/montecarlo.o

# target to build an object file
Solvers/montecarlo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/montecarlo.cpp.o
.PHONY : Solvers/montecarlo.cpp.o

Solvers/montecarlo.i: Solvers/montecarlo.cpp.i
.PHONY : Solvers/montecarlo.i

# target to preprocess a source file
Solvers/montecarlo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/montecarlo.cpp.i
.PHONY : Solvers/montecarlo.cpp.i

Solvers/montecarlo.s: Solvers/montecarlo.cpp.s
.PHONY : Solvers/montecarlo.s

# target to generate assembly for a file
Solvers/montecarlo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/Solvers/montecarlo.cpp.s
.PHONY : Solvers/montecarlo.cpp.s

WaveFunctions/interactinggaussian.o: WaveFunctions/interactinggaussian.cpp.o
.PHONY : WaveFunctions/interactinggaussian.o

# target to build an object file
WaveFunctions/interactinggaussian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/interactinggaussian.cpp.o
.PHONY : WaveFunctions/interactinggaussian.cpp.o

WaveFunctions/interactinggaussian.i: WaveFunctions/interactinggaussian.cpp.i
.PHONY : WaveFunctions/interactinggaussian.i

# target to preprocess a source file
WaveFunctions/interactinggaussian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/interactinggaussian.cpp.i
.PHONY : WaveFunctions/interactinggaussian.cpp.i

WaveFunctions/interactinggaussian.s: WaveFunctions/interactinggaussian.cpp.s
.PHONY : WaveFunctions/interactinggaussian.s

# target to generate assembly for a file
WaveFunctions/interactinggaussian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/interactinggaussian.cpp.s
.PHONY : WaveFunctions/interactinggaussian.cpp.s

WaveFunctions/simplegaussian.o: WaveFunctions/simplegaussian.cpp.o
.PHONY : WaveFunctions/simplegaussian.o

# target to build an object file
WaveFunctions/simplegaussian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/simplegaussian.cpp.o
.PHONY : WaveFunctions/simplegaussian.cpp.o

WaveFunctions/simplegaussian.i: WaveFunctions/simplegaussian.cpp.i
.PHONY : WaveFunctions/simplegaussian.i

# target to preprocess a source file
WaveFunctions/simplegaussian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/simplegaussian.cpp.i
.PHONY : WaveFunctions/simplegaussian.cpp.i

WaveFunctions/simplegaussian.s: WaveFunctions/simplegaussian.cpp.s
.PHONY : WaveFunctions/simplegaussian.s

# target to generate assembly for a file
WaveFunctions/simplegaussian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/WaveFunctions/simplegaussian.cpp.s
.PHONY : WaveFunctions/simplegaussian.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vmc.dir/build.make CMakeFiles/vmc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vmc.dir/build.make CMakeFiles/vmc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vmc.dir/build.make CMakeFiles/vmc.dir/main.cpp.s
.PHONY : main.cpp.s

particle.o: particle.cpp.o
.PHONY : particle.o

# target to build an object file
particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/particle.cpp.o
.PHONY : particle.cpp.o

particle.i: particle.cpp.i
.PHONY : particle.i

# target to preprocess a source file
particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/particle.cpp.i
.PHONY : particle.cpp.i

particle.s: particle.cpp.s
.PHONY : particle.s

# target to generate assembly for a file
particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/particle.cpp.s
.PHONY : particle.cpp.s

sampler.o: sampler.cpp.o
.PHONY : sampler.o

# target to build an object file
sampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/sampler.cpp.o
.PHONY : sampler.cpp.o

sampler.i: sampler.cpp.i
.PHONY : sampler.i

# target to preprocess a source file
sampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/sampler.cpp.i
.PHONY : sampler.cpp.i

sampler.s: sampler.cpp.s
.PHONY : sampler.s

# target to generate assembly for a file
sampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/sampler.cpp.s
.PHONY : sampler.cpp.s

system.o: system.cpp.o
.PHONY : system.o

# target to build an object file
system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/system.cpp.o
.PHONY : system.cpp.o

system.i: system.cpp.i
.PHONY : system.i

# target to preprocess a source file
system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/system.cpp.i
.PHONY : system.cpp.i

system.s: system.cpp.s
.PHONY : system.s

# target to generate assembly for a file
system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vmclib.dir/build.make CMakeFiles/Vmclib.dir/system.cpp.s
.PHONY : system.cpp.s

timing.o: timing.cpp.o
.PHONY : timing.o

# target to build an object file
timing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timing.dir/build.make CMakeFiles/timing.dir/timing.cpp.o
.PHONY : timing.cpp.o

timing.i: timing.cpp.i
.PHONY : timing.i

# target to preprocess a source file
timing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timing.dir/build.make CMakeFiles/timing.dir/timing.cpp.i
.PHONY : timing.cpp.i

timing.s: timing.cpp.s
.PHONY : timing.s

# target to generate assembly for a file
timing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timing.dir/build.make CMakeFiles/timing.dir/timing.cpp.s
.PHONY : timing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Vmclib"
	@echo "... timing"
	@echo "... vmc"
	@echo "... Hamiltonians/anharmonicoscillator.o"
	@echo "... Hamiltonians/anharmonicoscillator.i"
	@echo "... Hamiltonians/anharmonicoscillator.s"
	@echo "... Hamiltonians/harmonicoscillator.o"
	@echo "... Hamiltonians/harmonicoscillator.i"
	@echo "... Hamiltonians/harmonicoscillator.s"
	@echo "... InitialStates/initialstate.o"
	@echo "... InitialStates/initialstate.i"
	@echo "... InitialStates/initialstate.s"
	@echo "... Solvers/metropolis.o"
	@echo "... Solvers/metropolis.i"
	@echo "... Solvers/metropolis.s"
	@echo "... Solvers/metropolishastings.o"
	@echo "... Solvers/metropolishastings.i"
	@echo "... Solvers/metropolishastings.s"
	@echo "... Solvers/montecarlo.o"
	@echo "... Solvers/montecarlo.i"
	@echo "... Solvers/montecarlo.s"
	@echo "... WaveFunctions/interactinggaussian.o"
	@echo "... WaveFunctions/interactinggaussian.i"
	@echo "... WaveFunctions/interactinggaussian.s"
	@echo "... WaveFunctions/simplegaussian.o"
	@echo "... WaveFunctions/simplegaussian.i"
	@echo "... WaveFunctions/simplegaussian.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... particle.o"
	@echo "... particle.i"
	@echo "... particle.s"
	@echo "... sampler.o"
	@echo "... sampler.i"
	@echo "... sampler.s"
	@echo "... system.o"
	@echo "... system.i"
	@echo "... system.s"
	@echo "... timing.o"
	@echo "... timing.i"
	@echo "... timing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

